### ISSUE TITLE
Timer bug

### ISSUE THREAD

**Issue by cursorweb** [Minnesota-Computer-Club/MCC-Website#50]
![image](https://user-images.githubusercontent.com/29520825/207738649-f350041e-7b22-49c8-89d8-f1ed8c6a68f9.png)

**Comment by mike-weiner** [comment]
This bug was bad programming on my part. 

Take a look at this line: https://github.com/Minnesota-Computer-Club/MCC-Website/blob/d7e999f7b09efacefe600f3bb6330a0ed8443583/components/Leaderboard/index.js#L168

I am telling the countdown for `Next Puzzle Unlocks In:` to count down to 12:01 AM (1 second after midnight) for the time that the next puzzle unlocks. However, this is the time the puzzle unlocks for the **east coast**. (`startOfTomorrow()` https://date-fns.org/v2.29.3/docs/startOfTomorrow  is a helper function from `date-fns` that gets midnight of the next day in the local time zone). 

One simple solution would be to countdown to 11:01 PM instead of 12:01 AM.

`date-fns` has a handy `subHours()` (https://date-fns.org/v2.29.3/docs/subHours) method that could be used to subtract an hour off of `startOfTomorrow()`. 

The problem with that solution is the countdown will still be wrong for anyone not in the `American/Chicago`. What we really need is a solution that counts down from midnight east cost time and then converts it to the user's local browser timezone. `date-fns-tz` (https://date-fns.org/v2.29.3/docs/Time-Zones) might be able to help with that. Or you can tackle this another way if you've got something in mind. 

Dates and times and timezones are hard.

**Comment by cursorweb** [comment]
i thought we could use UTC and with this we are able to subtract some hours to get to the actual [time](https://adventofcode.com/2022/about) UTC+5

does date-fns have something like this?

**Comment by mike-weiner** [comment]
Yes, that would be the better way to do it. 

We actually don't need `date-fns` for getting the UTC offset. Javascript has a built-in function to do this for us! (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset)

The puzzles release [at midnight EST/UTC-5](https://adventofcode.com/2022/about). We just have to convert that time into the user's local browser time. 

[`moment.js`](https://momentjs.com/timezone/) could also help us with this too.

**Comment by cursorweb** [comment]
alright, i guess i'll make a branch to fix this
